---
#----------------------------#
# Configs outside of .config #
#----------------------------#

oh_my_zsh:
  src_path: ~/.dotfiles/configs/.oh-my-zsh
  dst_path: ~/.oh-my-zsh
  is_directory: true
  is_symlink: false

tmux_dir:
  src_path: ~/.dotfiles/configs/.tmux
  dst_path: ~/.tmux
  is_directory: true
  is_symlink: false

omz_plugins:
  src_path: ~/.dotfiles/configs/omz-plugins
  dst_path: ~/.oh-my-zsh/custom
  is_directory: true
  is_symlink: false

manjaro_config:
  src_path: ~/.dotfiles/configs/.manjaro-config
  dst_path: ~/.manjaro-config
  is_directory: false
  is_symlink: true

p10k:
  src_path: ~/.dotfiles/configs/.p10k.zsh
  dst_path: ~/.p10k.zsh
  is_directory: false
  is_symlink: true

tmux_conf:
  src_path: ~/.dotfiles/configs/.tmux.conf
  dst_path: ~/.tmux.conf
  is_directory: false
  is_symlink: true

zshrc:
  src_path: ~/.dotfiles/configs/.zshrc
  dst_path: ~/.zshrc
  is_directory: false
  is_symlink: true

#------------------------#
# Configs inside .config #
#------------------------#

alacritty:
  src_path: ~/.dotfiles/configs/.config/alacritty
  dst_path: ~/.config/alacritty
  is_directory: true
  is_symlink: true

Code:
  src_path: ~/.dotfiles/configs/.config/Code
  dst_path: ~/.config/Code
  is_directory: true
  is_symlink: true

dunst:
  src_path: ~/.dotfiles/configs/.config/dunst
  dst_path: ~/.config/dunst
  is_directory: true
  is_symlink: true

fastfetch:
  src_path: ~/.dotfiles/configs/.config/fastfetch
  dst_path: ~/.config/fastfetch
  is_directory: true
  is_symlink: true

gtk3:
  src_path: ~/.dotfiles/configs/.config/gtk-3.0
  dst_path: ~/.config/gtk-3.0
  is_directory: true
  is_symlink: false

hypr:
  src_path: ~/.dotfiles/configs/.config/hypr
  dst_path: ~/.config/hypr
  is_directory: true
  is_symlink: true

kitty:
  src_path: ~/.dotfiles/configs/.config/kitty
  dst_path: ~/.config/kitty
  is_directory: true
  is_symlink: true

kvantum:
  src_path: ~/.dotfiles/configs/.config/Kvantum
  dst_path: ~/.config/Kvantum
  is_directory: true
  is_symlink: false

myde:
  src_path: ~/.dotfiles/configs/.config/myde
  dst_path: ~/.config/myde
  is_directory: true
  is_symlink: true

nvim:
  src_path: ~/.dotfiles/configs/.config/nvim
  dst_path: ~/.config/nvim
  is_directory: true
  is_symlink: true

nwg:
  src_path: ~/.dotfiles/configs/.config/nwg-look
  dst_path: ~/.config/nwg-look
  is_directory: true
  is_symlink: true

qt5ct:
  src_path: ~/.dotfiles/configs/.config/qt5ct
  dst_path: ~/.config/qt5ct
  is_directory: true
  is_symlink: false

qt6ct:
  src_path: ~/.dotfiles/configs/.config/qt6ct
  dst_path: ~/.config/qt6ct
  is_directory: true
  is_symlink: false

rofi:
  src_path: ~/.dotfiles/configs/.config/rofi
  dst_path: ~/.config/rofi
  is_directory: true
  is_symlink: false

swaylock:
  src_path: ~/.dotfiles/configs/.config/swaylock
  dst_path: ~/.config/swaylock
  is_directory: true
  is_symlink: true

waybar:
  src_path: ~/.dotfiles/configs/.config/waybar
  dst_path: ~/.config/waybar
  is_directory: true
  is_symlink: false

wezterm:
  src_path: ~/.dotfiles/configs/.config/wezterm
  dst_path: ~/.config/wezterm
  is_directory: true
  is_symlink: true

wlogout:
  src_path: ~/.dotfiles/configs/.config/wlogout
  dst_path: ~/.config/wlogout
  is_directory: true
  is_symlink: false

kdeglobals:
  src_path: ~/.dotfiles/configs/.config/kdeglobals
  dst_path: ~/.config/kdeglobals
  is_directory: false
  is_symlink: false

#------------------------#
# Configs requiring sudo #
#------------------------#

sddm:
  src_path: ~/.dotfiles/configs/sddm/Candy
  dst_path: /usr/share/sddm/themes/Candy
  is_directory: true
  is_symlink: false
