---
#----------------------------#
# Configs outside of .config #
#----------------------------#

manjaro_config:
  src_path: ~/.dotfiles/configs/.manjaro-config
  dst_path: ~/.manjaro-config
  is_directory: false
  is_symlink: true

p10k:
  src_path: ~/.dotfiles/configs/.p10k.zsh
  dst_path: ~/.p10k.zsh
  is_directory: false
  is_symlink: true

tmux_conf:
  src_path: ~/.dotfiles/configs/.tmux.conf
  dst_path: ~/.tmux.conf
  is_directory: false
  is_symlink: true

zshrc:
  src_path: ~/.dotfiles/configs/.zshrc
  dst_path: ~/.zshrc
  is_directory: false
  is_symlink: true

#------------------------#
# Configs inside .config #
#------------------------#

dunst:
  src_path: ~/.dotfiles/configs/.config/dunst
  dst_path: ~/.config/dunst
  is_directory: true
  is_symlink: true

fastfetch:
  src_path: ~/.dotfiles/configs/.config/fastfetch
  dst_path: ~/.config/fastfetch
  is_directory: true
  is_symlink: true


hypr:
  src_path: ~/.dotfiles/configs/.config/hypr
  dst_path: ~/.config/hypr
  is_directory: true
  is_symlink: true

kvantum:
  src_path: ~/.dotfiles/configs/.config/Kvantum
  dst_path: ~/.config/Kvantum
  is_directory: true
  is_symlink: false

myde:
  src_path: ~/.dotfiles/configs/.config/myde
  dst_path: ~/.config/myde
  is_directory: true
  is_symlink: true

nvim:
  src_path: ~/.dotfiles/configs/.config/nvim
  dst_path: ~/.config/nvim
  is_directory: true
  is_symlink: true

nwg:
  src_path: ~/.dotfiles/configs/.config/nwg-look
  dst_path: ~/.config/nwg-look
  is_directory: true
  is_symlink: true

qt5ct:
  src_path: ~/.dotfiles/configs/.config/qt5ct
  dst_path: ~/.config/qt5ct
  is_directory: true
  is_symlink: false

qt6ct:
  src_path: ~/.dotfiles/configs/.config/qt6ct
  dst_path: ~/.config/qt6ct
  is_directory: true
  is_symlink: false

rofi:
  src_path: ~/.dotfiles/configs/.config/rofi
  dst_path: ~/.config/rofi
  is_directory: true
  is_symlink: false

waybar:
  src_path: ~/.dotfiles/configs/.config/waybar
  dst_path: ~/.config/waybar
  is_directory: true
  is_symlink: false

kdeglobals:
  src_path: ~/.dotfiles/configs/.config/kdeglobals
  dst_path: ~/.config/kdeglobals
  is_directory: false
  is_symlink: false
