#!/usr/bin/bash

current_year=$(date +%Y)
license="MIT License

Copyright (c) $current_year Mayank Sinha

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."


#Create root level directory using project name.
mkdir $1
cd $1

directories=(
# "data/external"
# "data/interim"
"data/processed"
"data/raw"
"docs"
"models"
"notebooks"
# "references"
# "reports/figures"
"src/models"
"src/data"
"src/utils"
)


files=(
"src/__init__.py"
"README.md"
"requirements.txt"
"Makefile"
)


echo "$license" > "LICENSE"
for dir in "${directories[@]}"; do
    mkdir -p "$dir"
    echo "Created directory: $dir"
done
for file in "${files[@]}"; do
    touch "$file"
    echo "Created file: $dir"
done
nvim .
