#!/bin/bash

source /home/mayank/Miniconda/bin/activate test

if [ -z "$2" ]
then
  python /home/mayank/Documents/personal_projects/development/timer.py --time $1
else
  source /home/mayank/Miniconda/bin/activate test
  python /home/mayank/Documents/personal_projects/development/timer.py --time $1 --file $2 
fi
# cod
